cloud/urls.py
from django.urls import path

from . import views
app_name = 'cloud'
urlpatterns = [
    path('', views.index, name='index'),
    path('files', views.files, name='files'),
    path('back_to_superior', views.back_to_superior, name='back_to_superior'),
    path('files/add_folder', views.add_folder, name='add_folder'),
    path('files/<folder_name>', views.go_to_folder, name='go_to_folder'),
    path('delete/<file>', views.delete_file, name='delete_file'),
    path('delete_folder/<folder>', views.delete_folder, name='delete_folder'),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path('upload', views.upload, name="upload"),
    path('share_file/<file>', views.share_file, name="share_file"),
    path('share/<file>', views.share, name="share"),
    path('stop_sharing/<file>', views.stop_sharing, name="stop_sharing"),
    path('rename/<folder>', views.rename, name="rename"),
    path('cut/<file>', views.cut, name="cut"),
    path('paste', views.paste, name="paste")
]

fucloud/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import  static

urlpatterns = [
    path('', include('cloud.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

"""link domyślny prowadzi do strony a plikacji cloud"""

cloud/models.py
from django.db import models
import datetime
import os
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.contrib.sessions.middleware import SessionMiddleware

class CustomUser(AbstractUser):
    pass
    available_space = models.FloatField(default=100)
    used_space = models.FloatField(default=0)
    creation_date = models.DateField(auto_now_add=True)
    directory = models.CharField(max_length=100,default='')

    def __str__(self):
        return f"{self.username},{self.creation_date} {self.available_space} {self.used_space}"

    def update_used_space(self, file_size):
        if self.used_space + file_size < self.available_space:
            self.used_space =  self.used_space + file_size
            self.save()
            return True
        else:
            return False

    def get_full_available_space(self):
        return self.available_space - self.used_space

    def get_available_space(self):
        return round((self.available_space - self.used_space)/(1024*1024) ,2)

    def get_used_percent(self):
        return round((self.used_space/self.available_space)*100,2)


class Folder(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=30)
    is_root = models.BooleanField(default=False)
    path = models.CharField(max_length=100)
    superior_path = models.CharField(max_length=100)

    def __str__(self):
        return self.name

def get_upload_path(instance, filename):
    return os.path.join(instance.user.username, filename)

class File(models.Model):
    name = models.CharField(max_length=40)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    size = models.FloatField(default=0)
    file = models.FileField(upload_to=get_upload_path,default='')
    is_shared = models.BooleanField(default=False)
    share_link = models.CharField(max_length=140, default="")

    def __str__(self):
        return f"{self.name}, size:{self.size}B"

class Context(models.Model):
    main_text_index = models.CharField(max_length = 40, default="FRIENDLY USER CLOUD")
    subtitle_index = models.CharField(max_length = 150, default="Przechowamy Twoje pliki :)")
    footer = models.CharField(max_length=150, default="CREATED BY KRZYSZTOF IŁENDO, MARCIN GRABOWIECKI AND ŁUKASZ HOSSA")
    login_link = models.CharField(max_length = 40, default="LOGIN")
    logout_link = models.CharField(max_length = 40, default="LOGOUT")
    register_link = models.CharField(max_length = 40, default="REGISTER")
    welcome_logged_user_link = models.CharField(max_length = 40, default="Welcome, ")
    welcome_user_files_view = models.CharField(max_length = 50, default="WITAJ")
    go_to_your_files_button = models.CharField(max_length = 40, default="Przejdź do swoich plików")
    subtitle_files_view = models.CharField(max_length = 50, default="Oto Twoje pliki")


    def __str__(self):
        return "Edytując ten obiekt możesz zmienić wartości wyświetlane na stronie"

cloud/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, File, Folder
import os
from django.conf import settings
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()

# Create your forms here.

class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2",)
        exclude = ("available_space",)

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        if commit:
            user.save()
        dirname = user.username # 2010.08.09.12.08.45
        try:
            path = os.path.join(settings.MEDIA_ROOT, dirname)
            os.mkdir(path)
            folder = Folder(user = user, name = user.username, is_root = True, path = path)
            folder.save()
        except:
            print("Błąd dodawania folderu")
        return user



class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('username', 'email')

class FileForm(forms.ModelForm):
    class Meta:
        model = File

        fields = [
            'file'
        ]
        exclude = [
            'size', 'user', 'name','is_shared',
        ]

class FolderForm(forms.ModelForm):

    class Meta:
        model = Folder

        fields = [
            'name'
        ]
        exclude = [
            'user', 'is_root', 'path', 'superior_path',
        ]

cloud/views.py
import os
from django.conf import settings
from django.shortcuts import render, redirect
from django.db import models
from django.http import HttpResponse
from .models import File, Folder, CustomUser, Context
from .forms import NewUserForm, FileForm, FolderForm
from django.contrib.auth import login,authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sessions.middleware import SessionMiddleware
from django.contrib.auth.middleware import AuthenticationMiddleware
from django.core.files.storage import FileSystemStorage
from django.core.files.base import ContentFile


# Create your views here.
def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			user.available_space = request.POST['space']
			user.save()
			login(request, user)
			#messages.success(request, "Registration successful." )
			request.session['current_path'] = os.path.join(settings.MEDIA_ROOT, request.user.username)
			return redirect("cloud:files")
		messages.error(request, "Rejestracja nie powiodła się.")
	form = NewUserForm
	context = get_context()
	context["register_form"] = form
	return render (request=request, template_name="cloud/register.html", context=context)

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)

			if user is not None:
				login(request, user)
				#messages.info(request, f"You are now logged in as {username}.")
				user = request.user
				#current_path = Folder.objects.get(user = user)
				#current_path = "cloud/files/files/{0}".format(user.username)
				request.session['current_path'] = os.path.join(settings.MEDIA_ROOT, request.user.username)
				return redirect ('cloud:files')
			else:
				messages.error(request,"Niepoprawna nazwa użytkownika lub hasło.")
		else:
			messages.error(request,"Niepoprawna nazwa użytkownika lub hasło.")
	form = AuthenticationForm()
	context = get_context()
	context["login_form"] = form
	return render(request=request, template_name="cloud/login.html", context=context)

def logout_request(request):
	logout(request)
	#messages.success(request, "You have successfully logged out.")
	return redirect('cloud:index')

def files(request):
	if request.user.is_authenticated:
		#files_list = File.objects.filter(user = request.user)
		path = request.session.get('current_path')
		current_folder = Folder.objects.get(path = path)
		#files_list, directory_list = prepare_file_list(os.listdir(path))
		files_list=[]

		for file in File.objects.all():
			if file.user == request.user:
				if file.folder.path == request.session['current_path']:
					files_list.append(file)

		folder_list = []

		for folder in Folder.objects.all():
			if folder.user == request.user:
				if folder.superior_path == request.session['current_path']:
					folder_list.append(folder)

		context = get_context()
		context['files_list']=files_list
		context['username']=request.user.username
		context['directory_list']:folder_list
		context['is_root']=current_folder.is_root
		context['directory_list'] = folder_list
		context['available_space'] = request.user.get_available_space()
		context['used_space_percent'] = request.user.get_used_percent()

		return render(request, 'cloud/files.html',context)
	else:
		return redirect('cloud:index')



def go_to_folder(request, folder):
	return redirect('cloud:index')

def index(request):
	context = get_context()
	return render(request, 'cloud/index.html', context)

def logout_view(request):
	logout(request)
	return render('cloud:index')

def profile_mail(request,username):
	u = User.object.get(username = username)

def upload(request):
	if request.user.is_authenticated:
		username = request.user.username
		if request.method == 'POST':
			form = FileForm(request.POST, request.FILES)
			if form.is_valid():
				if request.user.update_used_space(request.FILES['file'].size):
					uploadedFile = form.save(commit=False)
					uploadedFile.user = request.user
					uploadedFile.size = request.FILES['file'].size
					current_folder = Folder.objects.get(path = request.session['current_path'])
					uploadedFile.folder = current_folder
					uploadedFile.name = request.FILES['file'].name
					uploadedFile.is_shared = False
					uploadedFile.save()
					context = get_context()
					context["form"] = FileForm()
					context["uploaded_file_url"] = uploadedFile.file.url
					context["username"]=username
					return redirect('cloud:files')
					#return render(request, 'cloud/files.html', context)
				else:
					form = FileForm()
					context = get_context()
					context["form"] = FileForm()
					context["too_large_file"] = True
					context['available_space'] = request.user.get_available_space()
				return render(request, 'cloud/upload.html', context)
		else:
			form = FileForm()
			context = get_context()
			context["form"] = FileForm()
			context['available_space'] = request.user.get_available_space()
		return render(request, 'cloud/upload.html', context)
	else:
		return redirect('cloud:index')

def add_folder(request):
	if request.user.is_authenticated:
		if request.method == 'POST':
			form = FolderForm(request.POST)
			if form.is_valid():
				superior_folder = Folder.objects.get(path=request.session['current_path'])
				new_path = os.path.join(superior_folder.path, request.POST['name'])
				if Folder.objects.filter(path=new_path).count() <1:
					added_folder = form.save(commit=False)
					added_folder.user = request.user
					superior_folder = Folder.objects.get(path = request.session['current_path'])
					added_folder.superior_path = superior_folder.path
					added_folder.is_root = False
					new_path = os.path.join(superior_folder.path, added_folder.name)
					added_folder.path = new_path
					added_folder.save()
					return render(request, 'cloud/add_folder.html', {
						"form": FolderForm(),
						"added_folder": added_folder.path,
					})
				form = FolderForm()
				context = get_context()
				context["form"] = form
				context["same_name"]=True
				return render(request, 'cloud/add_folder.html', context)
		else:
			form = FolderForm()
			context = get_context()
			context["form"] = form
		return render(request, 'cloud/add_folder.html', context)
	else:
		return redirect('cloud:index')

def go_to_folder(request, folder_name):
	if request.user.is_authenticated:
		new_path = os.path.join(request.session['current_path'],folder_name)
		request.session['current_path'] = new_path
		return redirect('cloud:files')
	else:
		return redirect('cloud:index')

def back_to_superior(request):
	current_folder = Folder.objects.get(path = request.session['current_path'])
	if current_folder.is_root == False:
		request.session['current_path'] = current_folder.superior_path
	return redirect('cloud:files')

def  delete_file(request, file):
	if request.user.is_authenticated:
		id_del = file
		del_file = File.objects.get(id=id_del)
		request.user.update_used_space((del_file.file.size)*-1)

		os.remove(del_file.file.path)
		File.objects.filter(id=id_del).delete()
		return redirect('cloud:files')
	else:
		return redirect('cloud:index')

def delete_folder(request, folder):
	if request.user.is_authenticated:
		del_folder = Folder.objects.get(id=folder)
		files = File.objects.all()
		folders = Folder.objects.all()
		for file in files:
			if file.user == request.user:
				if file.folder == del_folder:
					request.user.update_used_space((file.file.size) * -1)
					os.remove(file.file.path)
					File.objects.get(id=file.id).delete()
		for folder in folders:
			if folder.user == request.user:
				if del_folder.path == folder.superior_path:
					delete_folder_rek(request.user,folder)
		#os.rmdir(os.path.join(settings.MEDIA_ROOT,request.user.username,del_folder.name))
		del_folder.delete()
		return redirect('cloud:files')
	else:
		return redirect('cloud:index')


def delete_folder_rek(user,del_folder):
	files = File.objects.all()
	folders = Folder.objects.all()
	for file in files:
		if file.user == user:
			if file.folder == del_folder:
				user.update_used_space((file.file.size) * -1)
				os.remove(file.file.path)
				File.objects.get(id=file.id).delete()
	for folder in folders:
		if folder.user == user:
			if del_folder.path == folder.superior_path:
				delete_folder_rek(user,folder)
	del_folder.delete()
	return

def get_context():
	context_object = Context.objects.get(id=1)
	context = {
		'main_text_index':context_object.main_text_index,
		'subtitle_index':context_object.subtitle_index,
		'footer':context_object.footer,
		'login_link':context_object.login_link,
		'logout_link':context_object.logout_link,
		'register_link':context_object.register_link,
		'welcome_user_files_view':context_object.welcome_user_files_view,
		'welcome_logged_user_link':context_object.welcome_logged_user_link,
		'go_to_your_files_button':context_object.go_to_your_files_button,
		'subtitle_files_view':context_object.subtitle_files_view,
	}
	return context

def share_file(request, file):
	if request.user.is_authenticated:
		File.objects.filter(id = file).update(is_shared = True)
		link = f"167.99.130.228/share/{file}"
		context = get_context()
		context['id_file'] = file
		context["shared_link"] = link

		return render(request, 'cloud/share_file.html', context)
	else:
		return redirect('cloud:index')

def share(request, file):
	shared_file = File.objects.get(id=file)
	if shared_file.is_shared:
		context = get_context()
		context['shared_file'] = shared_file
		if shared_file.file.size < 1024*1024:
			size= round(shared_file.file.size/1024,2)
			#
			context['shared_file_size'] = f"{size}KB"
		else:
			size = round(shared_file.file.size / 1024*1024,2)
			context['shared_file_size'] = f"{size}MB"
		return render(request, 'cloud/share.html', context)
	else:

cloud/templates/cloud/add_folder.html
{% extends 'cloud/base.html' %}

{% block content %}

<div class="upload">
    <div class="mainupload">
        <h1>Podaj nazwę katalogu:</h1>

        <form method="post">
                {% csrf_token %}
                <div class="element>"><input class="input" type="text" name="name" placeholder="Nazwa folderu"></div>
            <input class="buttupload" type="submit" value="Dodaj folder">
        </form>
        {% if added_folder %}
            <p>Success!</p>
        {% endif %}
        {% if same_name %}
            <p>Folder o tej nazwie już istnieje!</p>
        {% endif %}

        <a class="buttupload" href="{% url 'cloud:files' %}"><span>Powrót</span></a>
    </div>
</div>

{% endblock %}

cloud/templates/cloud/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>


	<meta charset="utf-8">
	<title>Fucloud</title>
	<link rel="stylesheet" type="text/css" href="{% static 'cloud/style.css' %}">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<div class="head">
<header>
    <div class="logo">
        <a href = "{%url 'cloud:index'%}"> <img src="{% static 'cloud/images/logo.png' %}"> <a/>
    </div>
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li class="nav-item">
        <a class="nav-link" href="/logout">{{ logout_link }}</a>
      </li>
      <li >
        <p class="nav-link"> {{ welcome_logged_user_link }} {{user.username}}</p>
      </li>
            {% else %}
            <li class="nav-item">
        <a class="nav-link" href="/login">{{ login_link }}</a>
        <a class="nav-link" href="/register">{{ register_link }}</a>

      </li>

      {% endif %}
        </ul>
    </nav>
</header>
    {% for message in messages %}

                    <div class="alert">
                            {{ message }}
                        <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>

                    </div>
            {% endfor %}
</div>
<div class="container">
 {% block content %}
    {% endblock %}

</div>

<footer>
    <p>{{ footer }}</p>
</footer>
</body>
</html>

cloud/templates/cloud/files.html
{% extends 'cloud/base.html' %}
{% load static %}


{% block content %}
<div class="files">
    <div class="minefiles">
        <h2>{{ welcome_user_files_view }} {{ username }} !</h2>
        <h1>{{ subtitle_files_view }}</h1>
        {% if is_root == False %}
        <p><a href="{% url 'cloud:back_to_superior' %}" class="buttback"><span><b>⋘</b></span></a></p>
        {%endif%}
        <table class="filetable">
            {% for folder in directory_list %}
            <tr>
                <td><a class="folder" href="{% url 'cloud:go_to_folder' folder.name%}"><img src="{% static 'cloud/images/folder.svg' %}" alt="folder.svg" height="15px" width="auto">  {{ folder }}</td>
                <td>
                    <a href="{% url 'cloud:delete_folder' folder.id %}" class="buttsave"><span>Usuń folder</span></a>
                </td>
                <td>
                    <form action="{% url 'cloud:rename' folder.id %}" method="post">
                        {% csrf_token %}
                        <input class="newname" type="text" name="new_name" required>
                        <input class="buttsave" type="submit" value="Zmień nazwę">
                    </form>
                </td>
            </tr>
            {% endfor %}
        </table>
        <table class="filetable">
            {% for file in files_list %}
            <tr>
                <td>{{ file.name }}</td>
                <td>
                    <a href="{{file.file.url}}" class="buttsave"><span>Pobierz plik</span></a>
                </td>
                <td>
                    <a href="{% url 'cloud:delete_file' file.id %}" class="buttsave"><span>Usuń</span></a>
                </td>
                {% if file.is_shared == False %}
                <td>
                    <a href="{% url 'cloud:share_file' file.id %}" class="buttsave"><span>Udostępnij</span></a>
                </td>
                {% else %}
                <td>
                    <a href="{% url 'cloud:stop_sharing' file.id %}" class="buttshare"><span>Przerwij udostępnianie</span></a>
                </td>
                {%endif%}
                 <td>
                    <a href="{% url 'cloud:cut' file.id %}" class="buttsave"><span>Wytnij</span></a>
                </td>

            </tr>
            {% endfor %}
       </table>

        <a href="{% url 'cloud:upload' %}" class="buttupload"><span>Dodaj plik</span><a>
        <a href="{% url 'cloud:add_folder' %}" class="buttupload"><span>Dodaj folder</span><a>
        <a href="{% url 'cloud:paste' %}" class="buttupload"><span>Wklej</span><a>


    </div>
<div class="space">
    <div class=element">
        <h3>Zajęta przestrzeń</h3>
        <progress class="file" max="100" value="{{ used_space_percent }}">{{ used_space_percent }}</progress>
        <p>Wolna przestrzeń: {{available_space}}MB</p>
    </div>
    <div>
</div>


    </div>
</div>


{% endblock %}

cloud/templates/cloud/index.html
{% extends 'cloud/base.html' %}

{% block content %}


<div class="container">
    <div class="main">
        <h1>{{ main_text_index }}</h1>
        <p>{{ subtitle_index }}</p>
        {% if user.is_authenticated %}
        <div class="butt3">
            <a href="/files"><button class="buttp"><span>{{ go_to_your_files_button }}</span></button></a>
            </div>
        {% else %}
        <div class="butt1">
            <a href="/login"><button class="butt"><span>LOG IN</span></button></a>
        </div>
        <div class="butt2">
            <a href="/register"><button class="butt"><span>SIGN UP</span></button></a>
        </div>
        {% endif %}
    </div>
</div>

{% endblock %}

cloud/templates/cloud/login.html
{% extends "cloud/base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Login-->
<div class="login">
  <h1>Log in</h1>
  <form method="POST">
    {% csrf_token %}
    <div class="element>"><input class="input" type="text" name="username" placeholder="Nazwa użytkownika"></div>
    <div class="element>"><input class="input" type="password" name="password" placeholder="Hasło"></div>
    <div class="element>"><button class="butt" type="submit"><span>Zaloguj się</span></button></div>
  </form>
  <p class="text-center">Nie posiadasz konta? <a href="/register">Dołącz do naszej chmury</a>.</p>
</div>

{% endblock %}

cloud/templates/cloud/register.html
{% extends "cloud/base.html" %}



{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="register">
	<h1>SIGN UP</h1>
	<form method="POST" novalidate>
		{% csrf_token %}
		<div class="element>"><input class="input" type="text" name="username" placeholder="Nazwa użytkownika"></div>
        <div class="element>"><input class="input" type="text" name="email" placeholder="Adres e-mail"></div>
        <div class="element>"><input class="input" type="password" name="password1" placeholder="Hasło"></div>
        <div class="element>"><input class="input" type="password" name="password2" placeholder="Powtórz hasło"></div>
	<div class="element>"><p>Wybierz rozmiar dysku</p>
		<div class="custom-select">
		<select name="space" required>
			<option value="314572800">300MB</option>
			<option value="314572800">300MB</option>
			<option value="524288000">500MB</option>
			<option value="838860800">800MB</option>
		</select>
		</div>
	</div>
		<div class="element>"><button class="butt" type="submit"><span>Zarejestruj się</span></button></div>
	</form>
	<p class="text-center">Masz już konto? <a href="/login">Zaloguj się</a> teraz.</p>
</div>

<script>
var x, i, j, l, ll, selElmnt, a, b, c;
x = document.getElementsByClassName("custom-select");
l = x.length;
for (i = 0; i < l; i++) {
  selElmnt = x[i].getElementsByTagName("select")[0];
  ll = selElmnt.length;
  a = document.createElement("DIV");
  a.setAttribute("class", "select-selected");
  a.innerHTML = selElmnt.options[selElmnt.selectedIndex].innerHTML;
  x[i].appendChild(a);
  b = document.createElement("DIV");
  b.setAttribute("class", "select-items select-hide");
  for (j = 1; j < ll; j++) {
    c = document.createElement("DIV");
    c.innerHTML = selElmnt.options[j].innerHTML;
    c.addEventListener("click", function(e) {
        var y, i, k, s, h, sl, yl;
        s = this.parentNode.parentNode.getElementsByTagName("select")[0];
        sl = s.length;
        h = this.parentNode.previousSibling;
        for (i = 0; i < sl; i++) {
          if (s.options[i].innerHTML == this.innerHTML) {
            s.selectedIndex = i;
            h.innerHTML = this.innerHTML;
            y = this.parentNode.getElementsByClassName("same-as-selected");
            yl = y.length;
            for (k = 0; k < yl; k++) {
              y[k].removeAttribute("class");
            }
            this.setAttribute("class", "same-as-selected");
            break;
          }
        }
        h.click();
    });
    b.appendChild(c);
  }
  x[i].appendChild(b);
  a.addEventListener("click", function(e) {
      e.stopPropagation();
      closeAllSelect(this);
      this.nextSibling.classList.toggle("select-hide");
      this.classList.toggle("select-arrow-active");
    });
}
function closeAllSelect(elmnt) {
  var x, y, i, xl, yl, arrNo = [];
  x = document.getElementsByClassName("select-items");
  y = document.getElementsByClassName("select-selected");
  xl = x.length;
  yl = y.length;
  for (i = 0; i < yl; i++) {
    if (elmnt == y[i]) {
      arrNo.push(i)
    } else {
      y[i].classList.remove("select-arrow-active");
    }
  }
  for (i = 0; i < xl; i++) {
    if (arrNo.indexOf(i)) {
      x[i].classList.add("select-hide");
    }
  }
}
document.addEventListener("click", closeAllSelect);
</script>

{% endblock %}

cloud/templates/cloud/rename.html
{% extends 'cloud/base.html' %}

{% block content %}
<div class="share">
 <form action="{% url %}">

 </form>
</div>
{% endblock %}

cloud/templates/cloud/share.html
{% extends 'cloud/base.html' %}

{% block content %}
<div class="share">
 <td>{{ shared_file.name }} {{shared_file_size}}</td>
    <p></p>
 <td>
   <a href="{{shared_file.file.url}}" class="buttupload"><span>Pobierz plik</span></a>
 </td>
</div>
{% endblock %}

cloud/templates/cloud/share_file.html
{% extends 'cloud/base.html' %}

{% block content %}

<div class="sharefile">
<p>Udostęponiony plik jest dostępny pod następującym linkiem: <a href="{%url 'cloud:share' id_file%}">{{shared_link}}</a></p>

<a class="buttupload" href="{% url 'cloud:files' %}"><span>Powrót</span></a>
</div>
{% endblock %}

cloud/templates/cloud/upload.html
{% extends 'cloud/base.html' %}
{%  load static %}

{% block content %}




<div class="upload">
    <div class="mainupload">
        <h1>Wybierz plik</h1>

        <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <input type="file" name="file" id="file" onchange = "Filevalidation()">
            <input class="buttupload" type="submit" value="Prześlij">
        </form>

        {% if uploaded_file_url %}
            <p>File uploaded at {{ uploaded_file_url }}</p>
        {% endif %}
        {% if too_large_file %}
            <p>Plik jest za duży</p>
        {% endif %}

        <a class="buttupload" href="{% url 'cloud:files' %}"><span>Powrót</span></a>
    </div>
</div>

<script>
    Filevalidation = () => {
        var available_space = "{{available_space}}";
        const fi = document.getElementById('file');
        if (fi.files.length > 0) {
            for (const i = 0; i <= fi.files.length - 1; i++) {

                const fsize = fi.files.item(i).size;
                const file = fsize;
                if (file >= available_space*1024*1024) {
                    alert(
                      "Plik jest za duży");
                        window.location.reload(true);
                }

                else {
                    document.getElementById('size').innerHTML = '<b>'
                    + file + '</b> KB';
                }
            }
        }
    }
</script>
{% endblock %}